#!/bin/bash
# Installs packages

echo "Running script.."

# Set up shell env
brc="$HOME/.bashrc"
echo "source $HOME/Config/main" > $brc; source $brc; shopt -s expand_aliases
sudo sed -i 's/#ParallelDownloads = 5/ParallelDownloads = 20/' /etc/pacman.conf
ecblock g "Set up shell env successful"

# Install official stuff
official=$(range $CONF/.packages/official)
if uuu && vvv $official; then
    ecblock yellow "Set up official stuff successful"
else
    ecr "Failure in the official stuff"
fi

# Configure git
gconfg core.editor "nvim"; git1=$?
gconfg user.email "dchooyc@gmail.com"; git2=$?
gconfg user.name "Daniel Choo"; git3=$?
git -C $CONF remote set-url origin git@github.com:dchooyc/Config.git; git4=$?
if [[ $git1 -eq 0 && $git2 -eq 0 && $git3 -eq 0 && $git4 -eq 0 ]]; then
    ecblock yellow "Git stuff configured"
else
    ecr "Failure configuring git stuff"
fi

# Set qbittorrent as default
xdg-mime default qbittorrent.desktop x-scheme-handler/magnet
magnet_default=$(xdg-mime query default x-scheme-handler/magnet)
ecblock yellow "$magnet_default set as default for magnet links"

# Install manual packages
man_packages="$CONF/.packages/manual"
if mm Packages && map amn $man_packages && cd; then
    ecblock yellow "Manual packages installed successfully"
else
    ecr "Failure in the manual packages stuff"
fi

# Install aur packages
aur_packages=$(range $CONF/.packages/aur)
if yyy $aur_packages; then
    ecblock yellow "Aur packages installed successfully"
else
    ecr "Failure in the aur packages stuff"
fi

# Import .confs and enable bluetooth
kimport; ni; kti; ess bluetooth

# Set ssh keys
ssh-keygen -t ed25519 -C "dchooyc@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub

ecblock g "Script has completed run"
